### ISSUE TITLE
Lithemobile theme Readability Issues with Add on Tags

### ISSUE THREAD

**Issue by VrijVlinder** [vanilla/community#100]
Please fix the issue of mobile theme add-on tag un-readability . 

Here is the code which does not exist in the theme but needs to be added to fix this. You can use other colors just make the contrast better because blue on grey is not readable on the mobile.

```
.Tag.Tag-Addon a{
color: #FCFF00;
text-shadow: 0 1px 0 #000;
}
.Tag.Tag-Addon {
background: #666;
}
```

Thanks

**Comment by linc** [comment]
Applied via Pocket
