### ISSUE TITLE
RSS source needs to be changed in getfeed

### ISSUE THREAD

**Issue by linc** [vanilla/community#126]
In the vforg app's `homeController_getFeed_create()` we get the product blog's announcements. This source needs to be changed from `https://blog.vanillaforums.com/category/dashboardnews/feed` to `https://blog.vanillaforums.com/topic/news/rss.xml` on Nov 1. A PR should be ready to go for then.

**Comment by adrianspeyer** [comment]
RSS Feed url will be 
https://blog.vanillaforums.com/rss.xml

Move will be tomorrow.
