### ISSUE TITLE
Addons Directory uploads fail due to incorrect path parsing

### ISSUE THREAD

**Issue by austins** [vanilla/community#135]
Uploading a normal addon such as an application with an addon.json file and no about.php fails with an empty red error box, similar to issue #128.

Upon debugging to find the error in Vanilla 2.5: an exception gets thrown in `handleAddonUpload()` when `UpdateModel::analyzeAddon()` is called.

`UpdateModel::analyzeAddon()` handles looking for and parsing an addon.json file in the `if (file_exists("$path/addon.json")) { ... }` block, but the problem is that $path is a path to a zip file, so it falls to the else block wherein `$entries = self::getInfoZip($path, $infoPaths, false, $throwError);` does not return any entries due to not having addon.json in $infoPaths.

The zip file should be processed before parsing addon.json.

**Comment by initvector** [comment]
Closed by https://github.com/vanilla/vanilla/pull/6863
