### ISSUE TITLE
Redirect loop causes by Private Community

### ISSUE THREAD

**Issue by Kaspar-K** [vanilla/community#143]
Vanilla 2.5.2 + 2.5.4
Having Private Community enabled (under Roles and Permissions) and setting forum in maintenance mode causes redirect loop (ERR_TOO_MANY_REDIRECTS) instead of showing "Maintenance Mode"-message for an not logged in instance.
Dashboard can still be accessed by admin.

**Comment by linc** [comment]
This repo is for the open.vanillaforums.com customizations. You're looking for https://github.com/vanilla/vanilla/issues

I also suggest using https://open.vanillaforums.com to post technical issues like this for further discussion before opening a bug ticket.
