### ISSUE TITLE
Google webmaster tools report that elements are too close together

### ISSUE THREAD

**Issue by MelVanilla** [vanilla/community#144]
Google webmaster tools is reporting that elements are too close together which makes it hard for people to click on mobile. 

Page affected: https://open.vanillaforums.com/addon/browse/plugins,applications/popular/p20

**Comment by DaazKu** [comment]
Can we have the actual warnings that the webmaster tools are reporting?

**Comment by DaazKu** [comment]
Mel checked the Webmaster tools again and fixing the broken images problems on the addons page seem to have resolve this issue!
