### ISSUE TITLE
Uploading Addon fails if addon.json is missing documentationUrl param

### ISSUE THREAD

**Issue by cchabilall83** [vanilla/community#145]
**Issue**
When trying to upload an addon zip at the addon/add endpoint, "Could not parse addon info array" error is thrown and the fileupload will fail if the addon.json is missing the documentationUrl param.  I've also notice that if file order is off that the issue will arise(tbc).  Missing the param shouldn't fail the upload, or worst case should throw a proper warning with more information.

This issue seems to be in this method

https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.updatemodel.php#L482

it returns an empty array, that is passed on this method where it fails.

https://github.com/vanilla/vanilla/blob/be968a0c3980140b61f3c559e096393368b09abc/applications/dashboard/models/class.updatemodel.php#L136

**Comment by charrondev** [comment]
Please don't touch that ancient `parseAddonInfo` method. Find the new equivalent in `Vanilla\Addon` and use that instead.
