### ISSUE TITLE
validateAddonKey is too strict

### ISSUE THREAD

**Issue by R-J** [vanilla/community#151]
I just tried to upload a plugin with the current naming conventions "some-word" and the addons key is the same "some-word". But I cannot upload it based on the validateAddonKey not accepting a minus sign: `-`

> The addon key cannot be a number and cannot contain any of the following characters: -,;:/\.

It's [that line](https://github.com/vanilla/community/blob/master/applications/addons/models/class.addonmodel.php#L786), that needs to be changed

**Comment by charrondev** [comment]
Yes it does.
