### ISSUE TITLE
GitHub forking banner is on top of third party login providers

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/community#26]
http://vanillaforums.org/discussions

"Fork me on GitHub" is on top (z-wise) of the top-right sign-in links, depending on screen width. Should have a lower z-index so I can actually click those things.

**Comment by hgtonight** [comment]
I tried mucking with the z-index in effort to make it work as expected. 

I couldn't get it to work. :(

**Comment by linc** [comment]
It can just get removed.
