### ISSUE TITLE
After signing in with Google+, it's asking me for GitHub and Password

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/community#27]
I have an account already. When I try to sign in with Google, I get this
![screenshot from 2015-05-20 09 17 27](https://cloud.githubusercontent.com/assets/583995/7727859/421fdb0c-fed1-11e4-95b5-e611b5adb7dd.png)

Is this asking for my GitHub login? If so, that seems pretty insecure.

Or is this just a mislabelled field?

**Comment by linc** [comment]
They are unrelated fields. The 'GitHub' field is being added by Profile Extender and is unrelated to the Password it wants. The minimum fix is to reverse the order of those fields (by moving the event that Profile Extender is using on that page) so at least 'Password' is associated with the account data above.

**Comment by JasonBarnabe** [comment]
If you did that, I think I would've understood that "Password" means "Vanilla password", but I'd still be utterly confused by "GitHub", both the presence of the field on this screen and what exactly it wants me to put in there. URL? User name? Password? I imagine someone who didn't have a GitHub account at all would be even more perplexed.

I don't see why it should be asking this on this screen at all.

**Comment by linc** [comment]
This is a workflow issue for core relating to how SSO & Profile Extender interact, not something to do with this repo's contents.
