### ISSUE TITLE
Latest version of Addon shows beta releases first

### ISSUE THREAD

**Issue by hgtonight** [vanilla/community#43]
This should be hidden to reduce confusion.

**Comment by linc** [comment]
There's a calculation problem with "latest version" generally. I also get redirected to the beta page whenever I'm managing releases (updating, approving) and it drives me nuts.

**Comment by linc** [comment]
I think we should break out pre-release versions **that are newer than the stable release** into a separate box below the version history, and hide all older pre-release versions.
